run:
	./quantum.sh

representation:
	python representation.py -p $(folder)/Data_plane.txt -x $(folder)/STABLE.xyz

plots:
	python plot.py -p $(folder)/energy_iteractions.txt -x $(folder)/energy_frequenciues.txt

